export const filterByName = (houses, query) => {
	query = query.toLowerCase();
	return houses.filter((item) =>
		item.name.split(' ').some((word) => word.toLowerCase().startsWith(query))
	);
};

const housingData = [
	{
		id: 1,
		address: '123 Maple St, Springfield, IL',
		price: 250000,
		bedrooms: 3,
		bathrooms: 2,
		squareFeet: 1800,
		type: 'Single Family',
		yearBuilt: 1995,
		listedDate: '2023-09-15',
		description:
			'Charming 3-bedroom house with a spacious backyard and modern kitchen.',
		features: ['Garage', 'Fireplace', 'Fenced Yard'],
		agent: {
			name: 'John Doe',
			contact: '555-1234',
			email: 'john@example.com',
		},
		status: 'For Sale',
	},
	{
		id: 2,
		address: '456 Oak Ave, Miami, FL',
		price: 350000,
		bedrooms: 4,
		bathrooms: 3,
		squareFeet: 2400,
		type: 'Condo',
		yearBuilt: 2010,
		listedDate: '2024-01-20',
		description:
			'Luxury condo with ocean views, modern amenities, and rooftop access.',
		features: ['Pool', 'Gym', 'Ocean View'],
		agent: {
			name: 'Jane Smith',
			contact: '555-5678',
			email: 'jane@example.com',
		},
		status: 'For Sale',
	},
	{
		id: 3,
		address: '789 Pine Ln, Austin, TX',
		price: 175000,
		bedrooms: 2,
		bathrooms: 1,
		squareFeet: 1200,
		type: 'Townhouse',
		yearBuilt: 2005,
		listedDate: '2024-03-05',
		description:
			'Cozy 2-bedroom townhouse in a quiet neighborhood, ideal for small families.',
		features: ['Patio', 'Near Park', 'Pet-Friendly'],
		agent: {
			name: 'Michael Johnson',
			contact: '555-8910',
			email: 'michael@example.com',
		},
		status: 'For Sale',
	},
	{
		id: 4,
		address: '101 Elm Dr, San Francisco, CA',
		price: 850000,
		bedrooms: 5,
		bathrooms: 4,
		squareFeet: 3200,
		type: 'Multi-Family',
		yearBuilt: 1970,
		listedDate: '2024-02-01',
		description:
			'Spacious multi-family home with great investment potential, close to downtown.',
		features: ['Balcony', 'Basement', 'City View'],
		agent: {
			name: 'Sara Lee',
			contact: '555-1239',
			email: 'sara@example.com',
		},
		status: 'Pending',
	},
	{
		id: 5,
		address: '202 Birch St, Denver, CO',
		price: 400000,
		bedrooms: 4,
		bathrooms: 3,
		squareFeet: 2100,
		type: 'Single Family',
		yearBuilt: 2015,
		listedDate: '2024-04-10',
		description:
			'Modern 4-bedroom home with open floor plan and mountain views.',
		features: ['Deck', 'Garage', 'Mountain View'],
		agent: {
			name: 'Alex Roberts',
			contact: '555-2345',
			email: 'alex@example.com',
		},
		status: 'For Sale',
	},
	{
		id: 6,
		address: '303 Cedar St, Seattle, WA',
		price: 600000,
		bedrooms: 3,
		bathrooms: 2,
		squareFeet: 1500,
		type: 'Single Family',
		yearBuilt: 2000,
		listedDate: '2024-03-25',
		description:
			'Beautiful 3-bedroom home in the heart of the city, close to all amenities.',
		features: ['Garden', 'Hardwood Floors', 'Near Public Transport'],
		agent: {
			name: 'Emily Clark',
			contact: '555-6789',
			email: 'emily@example.com',
		},
		status: 'For Sale',
	},
	{
		id: 7,
		address: '404 Willow Ave, Boston, MA',
		price: 725000,
		bedrooms: 4,
		bathrooms: 3,
		squareFeet: 2600,
		type: 'Townhouse',
		yearBuilt: 1998,
		listedDate: '2024-02-28',
		description:
			'Elegant townhouse with private patio and updated kitchen, located in a historic district.',
		features: ['Private Patio', 'Finished Basement', 'Historic Neighborhood'],
		agent: {
			name: 'David Green',
			contact: '555-3456',
			email: 'david@example.com',
		},
		status: 'For Sale',
	},
	{
		id: 8,
		address: '505 Spruce Dr, Phoenix, AZ',
		price: 275000,
		bedrooms: 3,
		bathrooms: 2,
		squareFeet: 1700,
		type: 'Single Family',
		yearBuilt: 2018,
		listedDate: '2024-03-15',
		description:
			'Energy-efficient home with solar panels, open layout, and desert landscaping.',
		features: ['Solar Panels', 'Desert Landscaping', 'Energy Efficient'],
		agent: {
			name: 'Rachel Adams',
			contact: '555-7890',
			email: 'rachel@example.com',
		},
		status: 'For Sale',
	},
	{
		id: 9,
		address: '606 Pine Ridge Rd, Dallas, TX',
		price: 500000,
		bedrooms: 5,
		bathrooms: 4,
		squareFeet: 3000,
		type: 'Single Family',
		yearBuilt: 2020,
		listedDate: '2024-01-10',
		description:
			'Large family home with a pool and open kitchen, perfect for entertaining.',
		features: ['Pool', 'Open Kitchen', 'Outdoor Living Space'],
		agent: {
			name: 'Chris Williams',
			contact: '555-5670',
			email: 'chris@example.com',
		},
		status: 'For Sale',
	},
	{
		id: 10,
		address: '707 Palm Blvd, Los Angeles, CA',
		price: 950000,
		bedrooms: 6,
		bathrooms: 5,
		squareFeet: 4000,
		type: 'Single Family',
		yearBuilt: 1985,
		listedDate: '2024-02-20',
		description:
			'Expansive 6-bedroom home with luxury finishes, pool, and private theater.',
		features: ['Pool', 'Private Theater', 'Luxury Finishes'],
		agent: {
			name: 'Olivia Martin',
			contact: '555-9087',
			email: 'olivia@example.com',
		},
		status: 'For Sale',
	},
];
